### ISSUE TITLE
restler grammar should support fuzzable elements for format: date-span and uri

### ISSUE THREAD

**Issue by marina-p** [microsoft/restler-fuzzer#11]
For the following Swagger defined properties:

```json
          "timeSpan": {
              "type": "string",
              "description": "A string which is interpreted as a TimeSpan",
              "format": "date-span",
              "nullable": true
            }

          "targetUrl": {
            "type": "string",
            "format": "uri",
            "nullable": true
          }
```

Currently, these are compiled to ```restler_fuzzable_string```.

It should instead be ```restler_fuzzable_date_span``` and ```restler_fuzzable_uri```.

**Comment by mbiuki** [comment]
Is there any property to use for DateTime strings such that their name from/to that is from the swagger translated to proper date-time string format?

For example, OpenAPI YAML:
```
        - in: query
          name: to
          description: You can find things that were raised before this time.
          docs-review: true
          schema:
            type: string
            format: datetime
```

instead of being translated to fuzzstring;
```
  "restler_fuzzable_string": [
    "fuzzstring"
  ],
```

Could it be translated to:

```
  "restler_fuzzable_datetime": [
    "2021-03-09T16:01:13Z"
  ],
```

And what is the short-term solution to bypass 400 errors b/c of the above problem?

**Comment by marina-p** [comment]
Hello @mbuki,

```restler_fuzzable_datetime``` can be used in the dictionary.  Are you saying that in the grammar.py these are ```restler_fuzzable_string```?  If yes, this looks like a bug - could you please copy/paste the grammar.py snippet you get for the above schema?  

As a workaround, you can use ```restler_custom_payload```, but values need to be specified separately for each of the parameters.  So, in the above:

```json
restler_custom_payload {
  "to": ["2021-03-09T16:01:13Z", "2021-03-10T16:01:13Z"],
  "from": ["2021-03-08T16:01:13Z", "2021-03-11T16:01:13Z"]
}
```  

Another less precise/verbose workaround would be to enter these values into the list of ```restler_fuzzable_string``` values.   This will cause more parameter combinations to be tried, but eventually RESTler should plug in those values into the query parameter.

**Comment by mbiuki** [comment]
Yes, in the grammar.py these are restler_fuzzable_string.

```
primitives.restler_static_string("from="),
primitives.restler_fuzzable_string("fuzzstring", quoted=False),
primitives.restler_static_string("&"),
primitives.restler_static_string("to="),
primitives.restler_fuzzable_string("fuzzstring", quoted=False),
primitives.restler_static_string("&"),
```


There are some additional notes here, so I am explaining from the beginning. 
When I run the following command from the root directory of my project where the YAML file is:

`Restler compile --api_spec openapi.yaml`

I get a new folder called `Compile' with all the default grammar, dict, etc. files. 

Looking into that generated dict.json, I also see that the datetime property is not in the right format, i.e.,

 ```
 "restler_fuzzable_datetime": [
    "6/25/2019 12:00:00 AM"
  ]
```
This is while the server only accepts ISO timestamps. e.g. "2021-02-09T16:54:13Z".

This is my openapi:

```
        - in: query
          name: from
          description: runtime after this time.
          schema:
            type: string
            format: datetime
        - in: query
          name: to
          description: runtime before this time.
          schema:
            type: string
            format: datetime
```

So I think issues are two here. One is datetime from schema to produce correct ISO format in dict.json and the second is to have this format create a correct datetime in grammar.py.

As a workaround, you can use restler_custom_payload, but values need to be specified separately for each of the parameters. So, in the above:

Even if I use:

```
restler_custom_payload {
  "to": ["2021-03-09T16:01:13Z", "2021-03-10T16:01:13Z"],
  "from": ["2021-03-08T16:01:13Z", "2021-03-11T16:01:13Z"]
}
```

The former issue persists, i.e., not ISO compliant.

Above all, note that our server does not need quotes around strings, which I see the quoted flag in grammar.py is set to False. So this should be fine as long as the problem from the above matters could be resolved, thanks.
