### ISSUE TITLE
Support fuzzing request header 

### ISSUE THREAD

**Issue by WaelAbuSeada** [microsoft/restler-fuzzer#156]
In some cases, we send some parameter in the request header, at the moment the compiler does not parse that, an example parameter:
   "parameters": [
          {
            "in": "header",
            "name": "serverComputerName",
            "description": "The name of the server computer (targetMachine).",
            "type": "string",
            "fullTypeName": "System.String"
          }
        ],

Can you please add support for this?

**Comment by mbiuki** [comment]
We have it similarly at our end and we would have to go in grammar.json and manually add the header param in.

This is what we have from the spec file:

```
parameters:
        - name: XYZ-ID
          in: header
          description: XYZ ID.
          required: true
          schema:
            type: string
            format: uuid
```

One suggestion could be to add custom header options for dictionary to construct the grammar.
