### ISSUE TITLE
Specify authentication for request

### ISSUE THREAD

**Issue by samuelspagl** [microsoft/restler-fuzzer#476]
Hey hey RESTler Team, 

is it possible to let RESTler know which authentication it will use for a given request. 
In our case, the same API uses both Bearer Authentication as well as Basic Authentication (only one for different requests of course) 
RN I think, is RESTler only adding the generated Authentication to the Header whether it is needed or not. The Problem is, if you try to use these two together, only one will be picked, because there should be only one `Authentification: <Type> <Value>` in a Request Header.

```yaml
  /v0/jwt_auth:
    get:
      summary:Jwt Authorization
      operationId: jwt_auth
      security:
        - BearerAuth: [ ]
      ...

/v0/basic_auth:
    get:
      summary: Basic Authorization
      operationId: basic_auth
      security:
        - BasicAuth: []
        ...
```

Wouldn't it be possible to reference the name of the authentication, in this case either `BearerAuth` or `BasicAuth` with the Metadata that needs to be printed for the token refresh command? Like: 

```python
    print("{u'BasicAuth': {},u'BearerAuth': {}, }")
    print("Authorization: Basic {0}".format(basic_b64_string))
    print("Authorization: Bearer {0}".format(token))
```

The result would be that requests, that don't have authentification defined in the openapi won't have anything included in the header, and for example `v0/jwt_auth` would have `Authorization:  Bearer <value>` and `v0/basic_auth` have `Authorization: Basic <value>`.

I'm looking forward hearing from you :)
