### ISSUE TITLE
JSON Pointers array indexes used in restler are not compliant with RFC 6901

### ISSUE THREAD

**Issue by Marcondiro** [microsoft/restler-fuzzer#816]
### Description

Restler exploits JSON pointers in OAS files in the `Link` objects and in the custom annotations, but the [examples](https://github.com/microsoft/restler-fuzzer/blob/99bc15988cd4c1e53bda1133728801d7d92061ff/docs/user-guide/Annotations.md?plain=1#L126C5-L126C5) and the parsing seem to use a different syntax with respect to the one defined in the [RFC 6901](https://datatracker.ietf.org/doc/html/rfc6901).
In particular the array indexes are surrounded by square brackets while the RFC doesn't allow them.

>    o  If the currently referenced value is a JSON array, the reference
>       token MUST contain either:
> 
>       *  characters comprised of digits (see ABNF below; note that
>          leading zeros are not allowed) that represent an unsigned
>          base-10 integer value, making the new referenced value the
>          array element with the zero-based index identified by the
>          token, or
> 
>       *  exactly the single character "-", making the new referenced
>          value the (nonexistent) member after the last array element.
> 
>    The ABNF syntax for array indices is:
> 
>    array-index = %x30 / ( %x31-39 *(%x30-39) )
>                  ; "0", or digits without a leading "0"

### Steps to reproduce

Compile an OpenAPI spec having a link like this
```
          links:
            fooLink:
              operationId: operation1
              parameters:
                foo: $response.body#/0/bar
```
It will be ignored by restler.

While a (non-standard) link like this will be used by restler:
```
          links:
            fooLink:
              operationId: operation1
              parameters:
                foo: $response.body#/[0]/bar
```
